dist: xenial
language: php
php:
- '7.2'
addons:
  sonarcloud:
    organization: "openva"
install:
- npm install && npm run build
- composer install --no-interaction --no-suggest --no-progress
script:
- ./docker-run.sh
- mkdir templates_c && chmod 777 templates_c
- ./run-tests.sh
- vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage-report.clover --log-junit=test-report.xml
- deploy/populate-secrets.sh
- sonar-scanner && zip -qr latest * && mkdir -p upload && mv latest.zip upload/latest.zip
deploy:
- provider: s3
  secret_access_key:
    secure: BzUcw4fme/C112XBT2cC4SbJzMifPawGWTKIUYr2bMLQZCZ2YRnEmiqH9Di7WfSEiUOwA7fQfZGn5411zkPx8NSxnG42+fD/dJNcFdsU9rcD1F4tuBN5C6Sgz6ZIgUt4NBrDPLGbsb+MLBkq001VKwqe4DUcS9O35qd7gwOUCos=
  access_key_id:
    secure: SK5Tbo/ZI0K9FyuEl5f4Pv2hZQGlWQxlUcgCpvZWUtXKu0fXRuQIZbCuXxpq+PhD0KS7P/pLCb5mXT5uom3gMhK3Xl9vUat0vVsFWNpFI4JnnAjmK9AZvM3dmmjztM87hU2fmDmIzB3Tx8s2IOpPCXQrb+LVrsXjRVAHe3FLk88=
  local_dir: upload
  skip_cleanup: true
  bucket: deploy.vabusinesses.org
  region: us-east-1
- provider: codedeploy
  secret_access_key:
    secure: BzUcw4fme/C112XBT2cC4SbJzMifPawGWTKIUYr2bMLQZCZ2YRnEmiqH9Di7WfSEiUOwA7fQfZGn5411zkPx8NSxnG42+fD/dJNcFdsU9rcD1F4tuBN5C6Sgz6ZIgUt4NBrDPLGbsb+MLBkq001VKwqe4DUcS9O35qd7gwOUCos=
  access_key_id:
    secure: SK5Tbo/ZI0K9FyuEl5f4Pv2hZQGlWQxlUcgCpvZWUtXKu0fXRuQIZbCuXxpq+PhD0KS7P/pLCb5mXT5uom3gMhK3Xl9vUat0vVsFWNpFI4JnnAjmK9AZvM3dmmjztM87hU2fmDmIzB3Tx8s2IOpPCXQrb+LVrsXjRVAHe3FLk88=
  bucket: deploy.vabusinesses.org
  key: latest.zip
  bundle_type: zip
  application: VA-Businesses
  deployment_group: VA-Businesses
  region: us-east-1
  wait-until-deployed: true
