version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/htdocs/
    container_name: vabusinesses
